version: "3.9"
services:
  integration_tests:
    build: ./integration_tests
    environment:
        REMOTE_URL: http://selenium-hub:4444/wd/hub
        CHALLENGE_API_URL: http://challenge-api:8080
        CHALLENGE_WEB_URL: http://challenge-web:3000
        IDENTITY_SERVER_URL: http://challenge-identity:80
        CLIENT_ID: robot-framework
        CLIENT_SECRET: secret
        SCOPE: challengeapi
        GRANT_TYPE: client_credentials
    volumes: [
        "$PWD/integration_tests/suites:/suites",
        "$PWD/integration_tests/scripts:/scripts",
        "$PWD/integration_tests/reports:/reports"
    ]
    networks:
      - code-challenge-network

networks:
  code-challenge-network:
    external:
      name: code_challenge_default
  