version: "3.9"
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    expose: 
      - 4444
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 40s
    networks:
        - code-challenge-network
  selenium-firefox-node:
    image: selenium/node-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - code-challenge-network

networks:
  code-challenge-network:
    external:
      name: code_challenge_default
  