version: "3.9"
services:
  postgres-db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: Secret!1
      POSTGRES_DB: test_database
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - code-challenge-network
  challenge-identity:
    build: ./challenge_identity
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - code-challenge-network
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
  challenge-api:
    build: ./challenge_api
    environment: 
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/test_database
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: http://challenge-identity:80/.well-known/openid-configuration/jwks
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://challenge-identity:80
    ports:
      - "8080:8080"
    networks:
      - code-challenge-network
    depends_on: 
      - postgres-db
      - challenge-identity
  challenge-web:
    build: ./challenge_web
    volumes:
      - './:/challenge_web'
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URI_LOCAL=http://localhost:8080
      - REACT_APP_IDENTITY_URI_LOCAL=http://localhost:5000
      - REACT_APP_REDIRECT_URI_LOCAL=http://localhost:3000/signin-oidc
      - REACT_APP_POST_LOGOUT_REDIRECT_URI_LOCAL=http://localhost:3000/signout-oidc
      - REACT_APP_API_URI_SELENIUM=http://challenge-api:8080
      - REACT_APP_IDENTITY_URI_SELENIUM=http://challenge-identity:80
      - REACT_APP_REDIRECT_URI_SELENIUM=http://challenge-web:3000/signin-oidc
      - REACT_APP_POST_LOGOUT_REDIRECT_URI_SELENIUM=http://challenge-web:3000/signout-oidc
      - REACT_APP_ENV=$REACT_APP_ENV
    networks:
      - code-challenge-network
    depends_on: 
      - challenge-api

networks:
  code-challenge-network:
    name: code_challenge_default

volumes:
      database-data: