name: Challenge CI
on: [push]
jobs:
  Challenge_CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Change wrapper permissions
        run: chmod +x ./challenge_api/mvnw
      - name: Build and run challenge API
        run: docker-compose -f docker-compose.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Run Selenium hub
        run: docker-compose -f docker-compose-selenium-hub.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Change script permissions
        run: chmod +x ./integration_tests/scripts/run_tests.sh
      - name: Run Integration tests
        run: docker-compose -f docker-compose-tests.yml up
      - name: Display structure after tests
        run: ls -R
      - name: Archive test results
        uses: actions/download-artifact@v2
        with:
          path: ./integration_tests/reports
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./integration_tests/reports