name: Challenge CI
on: [push]
jobs:
  Challenge_CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and run challenge API
        run: docker-compose -f docker-compose.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Run Selenium hub
        run: docker-compose -f docker-compose-selenium-hub.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Run Integration tests
        run: docker-compose -f docker-compose-tests.yml up -d
      - name: Check running containers
        run: docker ps -a